In [1]:
#DSC 550 Assignment 1
#Bilal Kudaimi
#March 19, 2021

import numpy as np
import pandas as pd

#Testing a smaller array first to make sure the program is running correctly
test_matrix = np.random.randint(1, 501, size=(3,2))
test_matrix_df = pd.DataFrame(test_matrix)
test_matrix_df

     0    1
0  420  486
1  445  456
2  340  225

In [2]:
#1: Now that the program is known to work, an array of size [10,50] is made and the random function 
#   is used to fill it with random integers between 1 and 500 before loading it into a data frame
rand_matrix = np.random.randint(1, 501, size=(10,50))
rand_matrix_df = pd.DataFrame(rand_matrix)
rand_matrix_df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,472,247,373,71,288,91,257,435,491,116,...,10,418,382,185,376,106,471,200,46,141
1,368,354,13,114,121,22,463,79,15,34,...,272,493,99,180,358,125,488,274,174,354
2,118,302,192,305,293,458,399,220,492,301,...,89,143,58,411,97,310,92,392,125,36
3,325,200,260,437,56,237,384,45,487,210,...,26,393,1,261,316,165,316,403,422,442
4,351,163,188,269,311,277,249,186,447,379,...,199,225,318,469,218,241,346,359,375,127
5,42,491,91,95,461,66,36,459,387,259,...,376,335,290,42,435,92,300,88,182,484
6,298,327,24,218,498,453,442,222,150,20,...,191,332,473,276,56,265,450,127,102,218
7,211,76,227,206,139,53,199,431,493,275,...,110,177,342,248,23,180,479,224,246,174
8,263,371,413,140,452,7,444,29,450,469,...,363,125,152,42,143,205,144,8,286,117
9,28,409,314,366,280,139,228,16,446,147,...,59,116,418,228,60,67,71,256,84,343

In [3]:
#2: Calculating the sum of each row, sum of each column, and sum of all entries.
row_sums = np.sum(rand_matrix_df, axis = 1) 
col_sums = np.sum(rand_matrix_df, axis = 0)
all_sums = np.sum(rand_matrix_df).sum()
print('Sums of each row: {}\n'.format(row_sums))
print('Sums of each column: {}\n'.format(col_sums))
print('Sums of all entries: {}'.format(all_sums))

Sums of each row: 0    12441
1    11764
2    12626
3    12438
4    12474
5    12152
6    14062
7    10586
8    12301
9    10252
dtype: int64

Sums of each column: 0     2476
1     2940
2     2095
3     2221
4     2899
5     1803
6     3101
7     2122
8     3858
9     2210
10    2900
11    2441
12    2650
13    2507
14    2578
15    2489
16    1894
17    2809
18    2845
19    3621
20    1755
21    2405
22    2345
23    2931
24    2176
25    1921
26    2952
27    1793
28    2375
29    2570
30    2108
31    1948
32    2935
33    2110
34    2996
35    2194
36    2087
37    1491
38    1668
39    2746
40    1695
41    2757
42    2533
43    2342
44    2082
45    1756
46    3157
47    2331
48    2042
49    2436
dtype: int64

Sums of all entries: 121096

In [4]:
#3: Determining the minimum, maximum, average, and standard deviation of all entries

minimum = np.min(rand_matrix_df).min()
maximum = np.max(rand_matrix_df).max()
average = np.mean(rand_matrix_df).mean()
standard_deviation = np.std(rand_matrix_df).std()
print('Minimum of all entries: {}\n'.format(minimum))
print('Maximum of all entries: {}\n'.format(maximum))
print('Average of all entries: {}\n'.format(average))
print('Standard deviation of all entries: {}'.format(standard_deviation))

Minimum of all entries: 1

Maximum of all entries: 499

Average of all entries: 242.19200000000012

Standard deviation of all entries: 20.54575837589276

In [5]:
#4: Sorting on column 2 and row 2

#Column 2 sorting first
rand_matrix_df.sort_values(by=1, axis=0)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
7,211,76,227,206,139,53,199,431,493,275,...,110,177,342,248,23,180,479,224,246,174
4,351,163,188,269,311,277,249,186,447,379,...,199,225,318,469,218,241,346,359,375,127
3,325,200,260,437,56,237,384,45,487,210,...,26,393,1,261,316,165,316,403,422,442
0,472,247,373,71,288,91,257,435,491,116,...,10,418,382,185,376,106,471,200,46,141
2,118,302,192,305,293,458,399,220,492,301,...,89,143,58,411,97,310,92,392,125,36
6,298,327,24,218,498,453,442,222,150,20,...,191,332,473,276,56,265,450,127,102,218
1,368,354,13,114,121,22,463,79,15,34,...,272,493,99,180,358,125,488,274,174,354
8,263,371,413,140,452,7,444,29,450,469,...,363,125,152,42,143,205,144,8,286,117
9,28,409,314,366,280,139,228,16,446,147,...,59,116,418,228,60,67,71,256,84,343
5,42,491,91,95,461,66,36,459,387,259,...,376,335,290,42,435,92,300,88,182,484

In [6]:
#Row 2 sorting
rand_matrix_df.sort_values(by = 1, axis = 1)

,2,8,24,5,37,9,16,14,21,7,...,1,44,0,10,17,6,32,46,41,19
0,373,491,275,91,124,116,337,290,21,435,...,247,376,472,275,15,257,25,471,418,471
1,13,15,17,22,34,34,55,66,79,79,...,354,358,368,411,457,463,469,488,493,499
2,192,492,172,458,19,301,262,448,114,220,...,302,97,118,362,10,399,402,92,143,461
3,260,487,362,237,227,210,322,130,294,45,...,200,316,325,287,482,384,215,316,393,396
4,188,447,429,277,396,379,20,174,400,186,...,163,218,351,42,28,249,51,346,225,298
5,91,387,16,66,48,259,16,323,458,459,...,491,435,42,282,499,36,487,300,335,378
6,24,150,232,453,29,20,410,494,358,222,...,327,56,298,179,481,442,335,450,332,195
7,227,493,131,53,14,275,129,80,387,431,...,76,23,211,303,495,199,388,479,177,364
8,413,450,306,7,414,469,154,376,114,29,...,371,143,263,339,168,444,451,144,125,120
9,314,446,236,139,186,147,189,197,180,16,...,409,60,28,420,174,228,112,71,116,439